### ISSUE TITLE
[Museformer] Data Process Encountered TypeErrors (have stetted to [General Use])

### ISSUE THREAD

**Issue by guan-yuan** [microsoft/muzic#102]
I encountered the following error when using MidiProcessor for data processing (follow the steps in README).

`
Traceback (most recent call last):
  File "/home/guanyuan/miniconda3/envs/diffsinger/lib/python3.8/site-packages/midiprocessor/batch_encoding.py", line 98, in process_file
    encodings = encoder.encode_file(
  File "/home/guanyuan/miniconda3/envs/diffsinger/lib/python3.8/site-packages/midiprocessor/midi_encoding.py", line 255, in encode_file
    midi_obj = midi_utils.load_midi(file_path, midi_checker=midi_checker)
  File "/home/guanyuan/miniconda3/envs/diffsinger/lib/python3.8/site-packages/midiprocessor/midi_utils.py", line 12, in load_midi
    midi_obj = miditoolkit.midi.parser.MidiFile(filename=file_path, file=file)
TypeError: __init__() got an unexpected keyword argument 'filename'
`

In addition, I found that MidiProcessor has been updated in the last month. Is this the reason for this error (some bugs of MidiProcessor need to be corrected)?

Thanks.

**Comment by guan-yuan** [comment]
more info

![image](https://user-images.githubusercontent.com/20538076/217793440-e8224bb9-6218-441f-991b-fbcb82b0a1ff.png)

**Comment by bdim404** [comment]
Same problem, and the `miditoolkit==0.1.16` can't sole the problem.
