### ISSUE TITLE
[museformer]RuntimeError: Error(s) in loading state_dict for MuseformerLanguageModel:

### ISSUE THREAD

**Issue by 233AvavAvA** [microsoft/muzic#114]
Traceback (most recent call last):
  File "/root/miniconda3/envs/my-env/bin/fairseq-interactive", line 8, in <module>
    sys.exit(cli_main())
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/fairseq_cli/interactive.py", line 307, in cli_main
    distributed_utils.call_main(args, main)
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/fairseq_cli/interactive.py", line 143, in main
    models, _model_args = checkpoint_utils.load_model_ensemble(
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 250, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 287, in load_model_ensemble_and_task
    model.load_state_dict(state["model"], strict=strict, args=args)
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/fairseq/models/fairseq_model.py", line 99, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/root/miniconda3/envs/my-env/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1482, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for MuseformerLanguageModel:
        size mismatch for decoder.embed_regular_tokens.weight: copying a param with shape torch.Size([560, 512]) from checkpoint, the shape in current model is torch.Size([1024, 512]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([560, 512]) from checkpoint, the shape in current model is torch.Size([1024, 512]).

I tried modify **checkpoint_utils.py**   and   **fairseq_model.py**      strict=False     but it didnt work

HELP ^V^

**Comment by lancelotblanchard** [comment]
Hey, I know this is quite old but for anyone having this issue: I believe that the checkpoint that is provided is built using the state dictionary `data/meta/dict.txt` rather than the [General Use] one `data/meta/general_use_dict.txt`. After remaking the binary data using the correct dictionary, I was able to run inference using the checkpoint.
