### ISSUE TITLE
error running getmusic trainning on windows

### ISSUE THREAD

**Issue by kotaxyz** [microsoft/muzic#124]
hello there thanks alot for this awesome project ,i was able to make infereing run on my system but when i try to train my own dataset i get this error 

(getmusic) C:\Users\Genesis\anaconda3\muzic\getmusic>python preprocess/to_oct.py example_data/train example_data/processed_train
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\spawn.py", line 125, in _main
    prepare(preparation_data)
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\runpy.py", line 265, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\runpy.py", line 97, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Genesis\anaconda3\muzic\getmusic\preprocess\to_oct.py", line 32, in <module>
    manager = Manager()
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\context.py", line 57, in Manager
    m.start()
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\managers.py", line 579, in start
    self._process.start()
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\popen_spawn_win32.py", line 45, in __init__
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "C:\Users\Genesis\anaconda3\envs\getmusic\lib\multiprocessing\spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError:
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

**Comment by trestad** [comment]
We did not test our code on Windows. Perhaps this helps: https://stackoverflow.com/questions/69515321/an-attempt-has-been-made-to-start-a-new-process-before-the-current-process-has-f.

According to this answer, you may need to move 'manager = Manager()' to within the if __name__ = '__main__': block.
