### ISSUE TITLE
[EmoGen] Torch and CUDA version

### ISSUE THREAD

**Issue by yc-li20** [microsoft/muzic#150]
There are a few version errors when running the code. Which version of Torch and CUDA should be used?

**Comment by yc-li20** [comment]
When running **bash Piano_train.sh**

Traceback (most recent call last):
  File "train.py", line 357, in <module>
    cli_main()
  File "train.py", line 353, in cli_main
    distributed_utils.call_main(args, main)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "train.py", line 96, in main
    trainer = Trainer(args, task, model, criterion, quantizer)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/fairseq/trainer.py", line 69, in __init__
    self._model = self._model.to(device=self.device)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1145, in to
    return self._apply(convert)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/torch/nn/modules/module.py", line 797, in _apply
    module._apply(fn)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/torch/nn/modules/module.py", line 820, in _apply
    param_applied = fn(param)
  File "/anaconda/envs/chao/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1143, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
RuntimeError: CUDA error: the provided PTX was compiled with an unsupported toolchain.
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by yc-li20** [comment]
solved
