### ISSUE TITLE
[MuseCoCo] attribute2music generate error

### ISSUE THREAD

**Issue by Journey7331** [microsoft/muzic#151]
Thank you very much for your team's contribution for this great works!

I follow your instruction in musecoco/README.md, 
when i run this code
```
    # II. Attribute-to-Music Generation 
    # The following script takes "data/infer_input/infer_test.bin" as input.
    bash interactive_1billion.sh 0 200
    # bash interactive.sh start_idx end_idx input_name
```

i got a error like this
```
    File "/usr/local/lib/python3.8/site-packages/fast_transformers/causal_product/__init__.py", line 44, in forward
        CausalDotProduct.dot[device.type](
    TypeError: 'NoneType' object is not callable
```

The original error message is as follows
```
Traceback (most recent call last):
  File "interactive_dict_v5_1billion.py", line 433, in <module>
    cli_main()
  File "interactive_dict_v5_1billion.py", line 423, in cli_main
    attributes(args)
  File "interactive_dict_v5_1billion.py", line 352, in attributes
    translations = task.inference_step(
  File "/usr/local/lib/python3.8/site-packages/fairseq/tasks/language_modeling.py", line 313, in inference_step
    return generator.generate(
  File "/usr/local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/command_seq_generator.py", line 179, in generate
    return self._generate(sample, **kwargs)
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/command_seq_generator.py", line 315, in _generate
    lprobs, avg_attn_scores = self.model.forward_decoder(
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/command_seq_generator.py", line 837, in forward_decoder
    decoder_out = model.decoder.forward(tokens, sep_pos, encoder_out=encoder_out)
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/transformer.py", line 193, in forward
    x, extra = self.extract_features(
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/transformer.py", line 216, in extract_features
    return self.extract_features_scriptable(
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/transformer.py", line 363, in extract_features_scriptable
    x, layer_attn, _ = layer(
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/transformer_layer.py", line 58, in forward
    x, attn = self.run_self_attn(
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/transformer_layer.py", line 117, in run_self_attn
    r = self.self_attn(query, query, query, attn_mask=None, key_padding_mask=key_padding_mask)
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/attention_layer.py", line 114, in forward
    new_values = self.inner_attention(
  File "/usr/local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/causal_linear_attention.py", line 70, in forward
    V = causal_linear(
  File "/content/drive/.shortcut-targets-by-id/1jpYMr2ZASgh-ocgmVjIxEo4ckn5kGPvN/muzic/musecoco/2-attribute2music_model/linear_mask/linear/causal_linear_attention.py", line 23, in causal_linear
    V_new = causal_dot_product(Q, K, V)
  File "/usr/local/lib/python3.8/site-packages/fast_transformers/causal_product/__init__.py", line 44, in forward
    CausalDotProduct.dot[device.type](
TypeError: 'NoneType' object is not callable
```

Have you ever encountered this problem? 
I'd appreciate it if you could help me out
Again, Thank your greatest contribution for this great works!

**Comment by Jackl-o-o-l** [comment]
I get the same problem and believe that there is something wrong with the installed package `pytorch-fast-transformers` 
idiap/fast-transformers#125

**Comment by Journey7331** [comment]
Agree with u, but it seems that this repo and `pytorch-fast-transformers` repo are not looking at issues. :(

**Comment by Jackl-o-o-l** [comment]
I have solved the issue. Please check idiap/fast-transformers#125

**Comment by Journey7331** [comment]
@Jackl-o-o-l  thank you a lot :)   it work now
