### ISSUE TITLE
models.ARCH_MODEL_REGISTRY[state["args"].arch]

### ISSUE THREAD

**Issue by XWQlover** [microsoft/muzic#152]
i get a error like this 

`Traceback (most recent call last):
  File "interactive_dict_v5_1billion.py", line 430, in <module>
    cli_main()
  File "interactive_dict_v5_1billion.py", line 420, in cli_main
    attributes(args)
  File "interactive_dict_v5_1billion.py", line 199, in attributes
    models, _model_args = checkpoint_utils.load_model_ensemble(
  File "/home/disk2/wangjunhao01/anaconda3/envs/MuseCoco/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 253, in load_model_ensemble
    ensemble, args, _task = load_model_ensemble_and_task(
  File "/home/disk2/wangjunhao01/anaconda3/envs/MuseCoco/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 282, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/disk2/wangjunhao01/anaconda3/envs/MuseCoco/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 235, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/home/disk2/wangjunhao01/anaconda3/envs/MuseCoco/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 439, in _upgrade_state_dict
    registry.set_defaults(state["args"], models.ARCH_MODEL_REGISTRY[state["args"].arch])
KeyError: 'linear_transformer_lm_1billion'`

**Comment by XWQlover** [comment]
Traceback (most recent call last):
  File "interactive_dict_v5_1billion.py", line 33, in <module>
    from linear import transformer_lm
  File "/home/disk2/xiaoweiqi/music/muzic-main/musecoco/2-attribute2music_model/linear_mask/linear/transformer_lm.py", line 6, in <module>
    from .transformer import LinearTransformerDecoder
  File "/home/disk2/xiaoweiqi/music/muzic-main/musecoco/2-attribute2music_model/linear_mask/linear/transformer.py", line 23, in <module>
    from .transformer_layer import LinearTransformerDecoderLayer
  File "/home/disk2/xiaoweiqi/music/muzic-main/musecoco/2-attribute2music_model/linear_mask/linear/transformer_layer.py", line 5, in <module>
    from .causal_linear_attention import CausalLinearAttention
  File "/home/disk2/xiaoweiqi/music/muzic-main/musecoco/2-attribute2music_model/linear_mask/linear/causal_linear_attention.py", line 12, in <module>
    from fast_transformers.causal_product import causal_dot_product
  File "/home/disk2/wangjunhao01/anaconda3/envs/MuseCoco/lib/python3.8/site-packages/fast_transformers/causal_product/__init__.py", line 9, in <module>
    from .causal_product_cpu import causal_dot_product as causal_dot_product_cpu, \
ImportError: /home/disk2/wangjunhao01/anaconda3/envs/MuseCoco/lib/python3.8/site-packages/fast_transformers/causal_product/causal_product_cpu.cpython-38-x86_64-linux-gnu.so: undefined symbol: _ZN2at4_ops5zeros4callEN3c108ArrayRefINS2_6SymIntEEENS2_8optionalINS2_10ScalarTypeEEENS6_INS2_6LayoutEEENS6_INS2_6DeviceEEENS6_IbEE
