### ISSUE TITLE
ckpt not found in checkpoints/0102_xiaoma_pe

### ISSUE THREAD

**Issue by takemars** [microsoft/muzic#179]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 6/6 [00:00<00:00,  9.06it/s]
| load 'model' from 'checkpoints/0228_opencpop_ds100_rel/model_ckpt_steps_160000.ckpt'.
Traceback (most recent call last):
  File "/data1/muzic/musicagent/gradio_agent.py", line 141, in <module>
    agent = MusicAgent(args.config, mode="gradio")
  File "/data1/muzic/musicagent/agent.py", line 41, in __init__
    self.pipes = init_plugins(self.config)
  File "/data1/muzic/musicagent/plugins.py", line 102, in init_plugins
    pipes["DiffSinger"] = DiffSinger(config)
  File "/data1/muzic/musicagent/plugins.py", line 294, in __init__
    self._init_toolkit(config)
  File "/data1/muzic/musicagent/plugins.py", line 308, in _init_toolkit
    self.model = DiffSingerE2EInfer(hparams, device="cuda:0")
  File "/data1/muzic/musicagent/models/DiffSinger/inference/svs/base_svs_infer.py", line 33, in __init__
    self.model = self.build_model()
  File "/data1/muzic/musicagent/models/DiffSinger/inference/svs/ds_e2e.py", line 28, in build_model
    utils.load_ckpt([self.pe](http://self.pe/), hparams['pe_ckpt'], 'model', strict=True)
  File "/data1/muzic/musicagent/models/DiffSinger/utils/__init__.py", line 207, in load_ckpt
    assert False, e_msg
AssertionError: | ckpt not found in checkpoints/0102_xiaoma_pe.

**Comment by sfdeggb** [comment]
I also meet this question. you need to download the all the checkpoint file form Hugging face  repository. Below is the download link.  https://huggingface.co/spaces/Silentlin/DiffSinger/tree/main. good luck
![image](https://github.com/microsoft/muzic/assets/95692531/4c24d432-edc9-43ae-a30c-54144344764d)
