### ISSUE TITLE
[teleMelody] Inference: How to get the dictionary placed in the data-bin?

### ISSUE THREAD

**Issue by plusoneee** [microsoft/muzic#36]
Hi, thanks for providing `checkpoints` of the models.
I'm trying to run the **inference**.  I got stuck on the line:
```python
data_name_or_path=f'data-bin/{lyric2beat_prefix}'
```
I put checkpoints in `telemelody/inferrence` like:
```
checkpoints
├── lyric2rhythm
│   └── checkpoint_best.pt
├── template2melody
│   └── checkpoint_best.pt
...
```
I'm not sure what file should be placed in `data-bin/model_prefix`. 
I will be grateful for any help you can provide.

**Comment by BILLXZY1215** [comment]
Hi, I guess the structure should be like this:
```
checkpoints
├── lyric2rhythm
│   └── checkpoint_best.pt
├── template2melody
│   └── checkpoint_best.pt
data-bin
├── lyric2rhythm
│   └── dict.beat.txt
│    ...
├── template2melody
│   └── dict.beat.txt
│    ...
```

The folders in `data-bin` are copied from `training/xxx/data-bin/yyy`.

**Comment by plusoneee** [comment]
@BILLXZY1215  Many thanks to you ! :)

**Comment by benfenison** [comment]
I have the following format below but keep getting an error:


checkpoints
├── lyric2rhythm
│   └── checkpoint_best.pt 
├── template2melody
│   └── checkpoint_best.pt
data-bin
├── lyric2rhythm
│   └── dict.beat.txt
    └── dict.lyric.txt
│    ...
├── template2melody
│   └── dict.trend.txt
    └── dict.note.txt
│    ...




Error:

2022-04-14 01:37:31 | INFO | fairseq.file_utils | loading archive file checkpoints/lyric2rhythm_en_best
2022-04-14 01:37:31 | INFO | fairseq.file_utils | loading archive file data-bin/lyric2rhythm_en_best
Traceback (most recent call last):
  File "infer_en.py", line 154, in <module>
    data_name_or_path=f'data-bin/{lyric2beat_prefix}',
  File "/usr/local/lib/python3.7/dist-packages/fairseq/models/fairseq_model.py", line 265, in from_pretrained
    **kwargs,
  File "/usr/local/lib/python3.7/dist-packages/fairseq/hub_utils.py", line 72, in from_pretrained
    arg_overrides=kwargs,
  File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 279, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/usr/local/lib/python3.7/dist-packages/fairseq/checkpoint_utils.py", line 231, in load_checkpoint_to_cpu
    setattr(args, arg_name, arg_val)
AttributeError: 'NoneType' object has no attribute 'data'


Should I only but the dict.beat.txt file in both? The txt file shouldn't have an attribute called 'data' right?

**Comment by jzq2000** [comment]
@benfenison  you can refer to this [link](https://github.com/microsoft/muzic/issues/29#issuecomment-1019877476)

**Comment by Hollie7** [comment]
pip install git+git://github.com/pytorch/fairseq.git@b8ea8a9b72c82192da07e3377adf4ebbde16716d 

that works
