### ISSUE TITLE
musicBert SMALL base MODEL error

### ISSUE THREAD

**Issue by jammyWolf** [microsoft/muzic#37]
when i run: $ bash train_mask.sh lmd_full small with provided small model,
fairseq gets error:

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/pyg/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/mmu_ssd/chenjunmin/apps/fairseq-0.10.0/fairseq/distributed_utils.py", line 270, in distributed_main
    main(args, **kwargs)
  File "/mmu_ssd/chenjunmin/apps/fairseq-0.10.0/fairseq_cli/train.py", line 114, in main
    disable_iterator_cache=task.has_sharded_data("train"),
  File "/mmu_ssd/chenjunmin/apps/fairseq-0.10.0/fairseq/checkpoint_utils.py", line 193, in load_checkpoint
    reset_meters=reset_meters,
  File "/mmu_ssd/chenjunmin/apps/fairseq-0.10.0/fairseq/trainer.py", line 279, in load_checkpoint
    state = checkpoint_utils.load_checkpoint_to_cpu(filename)
  File "/mmu_ssd/chenjunmin/apps/fairseq-0.10.0/fairseq/checkpoint_utils.py", line 232, in load_checkpoint_to_cpu
    state = _upgrade_state_dict(state)
  File "/mmu_ssd/chenjunmin/apps/fairseq-0.10.0/fairseq/checkpoint_utils.py", line 436, in _upgrade_state_dict
    registry.set_defaults(state["args"], tasks.TASK_REGISTRY[state["args"].task])
AttributeError: 'NoneType' object has no attribute 'task'

**Comment by mlzeng** [comment]
Currently, you can use a newer version of fairseq that will work on provided checkpoints.
```
git clone https://github.com/pytorch/fairseq
cd fairseq
git checkout 336942734c85791a90baa373c212d27e7c722662   # provided checkpoints are trained with this version
pip install --editable ./
```

**Comment by Asuka0002** [comment]
Hi, I tried 'bash train_nsp.sh next checkpoints/checkpoint_last_musicbert_base.pt ' and there occurs an error:

Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/tf2.2_ljw/bin/fairseq-train", line 33, in <module>
    sys.exit(load_entry_point('fairseq==1.0.0a0', 'console_scripts', 'fairseq-train')())
  File "/usr/local/anaconda3/envs/tf2.2_ljw/lib/python3.6/site-packages/fairseq-1.0.0a0-py3.6-linux-x86_64.egg/fairseq_cli/train.py", line 541, in cli_main
    parser = options.get_training_parser()
  File "/usr/local/anaconda3/envs/tf2.2_ljw/lib/python3.6/site-packages/fairseq-1.0.0a0-py3.6-linux-x86_64.egg/fairseq/options.py", line 38, in get_training_parser
    parser = get_parser("Trainer", default_task)
  File "/usr/local/anaconda3/envs/tf2.2_ljw/lib/python3.6/site-packages/fairseq-1.0.0a0-py3.6-linux-x86_64.egg/fairseq/options.py", line 234, in get_parser
    utils.import_user_module(usr_args)
  File "/usr/local/anaconda3/envs/tf2.2_ljw/lib/python3.6/site-packages/fairseq-1.0.0a0-py3.6-linux-x86_64.egg/fairseq/utils.py", line 491, in import_user_module
    importlib.import_module(module_name)
  File "/usr/local/anaconda3/envs/tf2.2_ljw/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/team5/l00519917/musicbert/musicbert/__init__.py", line 15, in <module>
    from fairseq.models.roberta import TransformerSentenceEncoder, RobertaEncoder, RobertaModel
ImportError: cannot import name 'TransformerSentenceEncoder'


I followed the above suggestion to install a newer version of  fairseq 1.0.0a0.  It seems that  TransformerSentenceEncoder is not in the model. Please help, thanks a lot.

**Comment by mlzeng** [comment]
Did you install the exact version?
git+https://github.com/pytorch/fairseq@336942734c85791a90baa373c212d27e7c722662#egg=fairseq

**Comment by Asuka0002** [comment]
Hi, I can't directly use git clone. Cloud you please tell me which exactly version is this: https://github.com/pytorch/fairseq@336942734c85791a90baa373c212d27e7c722662#egg=fairseq?

Is it fairseq v0.10.0?

**Comment by mlzeng** [comment]
It doesn't correspond to a released version, so you have to install it from git repo.

**Comment by Asuka0002** [comment]
Thanks a lot, problem sloved.
