### ISSUE TITLE
[ROC] Mistakes in training

### ISSUE THREAD

**Issue by CatherineJun** [microsoft/muzic#94]
When I trained the model, the error "FileNotFoundError: Dataset not found: valid (data/lmd_processed/valid)" appeared. How can i solve the problem?

**Comment by trestad** [comment]
Please (1) check whether 'data/lmd_processed/valid.notes' exists and (2) the training script is for fairseq 0.10.1, if you are using a higher version, check whether the command arguments change, e.g., the source or target need to be specified.

**Comment by gandolfxu** [comment]
@trestad 
Another mistake of traing.

Traceback (most recent call last):
  File "/opt/conda/envs/muzic/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/opt/conda/envs/muzic/lib/python3.8/site-packages/fairseq_cli/train.py", line 352, in cli_main
    distributed_utils.call_main(args, main)
  File "/opt/conda/envs/muzic/lib/python3.8/site-packages/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/opt/conda/envs/muzic/lib/python3.8/site-packages/fairseq_cli/train.py", line 110, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/opt/conda/envs/muzic/lib/python3.8/site-packages/fairseq/checkpoint_utils.py", line 212, in load_checkpoint
    epoch_itr = trainer.get_train_iterator(
  File "/opt/conda/envs/muzic/lib/python3.8/site-packages/fairseq/trainer.py", line 382, in get_train_iterator
    self.reset_dummy_batch(batch_iterator.first_batch)
  File "/opt/conda/envs/muzic/lib/python3.8/site-packages/fairseq/data/iterators.py", line 280, in first_batch
    raise Exception(
Exception: The dataset is empty. This could indicate that all elements in the dataset have been skipped. Try increasing the max number of allowed tokens or using a larger dataset.

**Comment by trestad** [comment]
According to your warning ''18505 samples have invalid sizes and will be skipped, max_positions=512", I guess that your data is so long that all of them are skipped. Perhaps you should use a larger 'max-target-position' like the excepption suggests: 'Exception: The dataset is empty. This could indicate that all elements in the dataset have been skipped. Try increasing the max number of allowed tokens or using a larger dataset.'
