### ISSUE TITLE
[Telemelody] RuntimeError: Error(s) in loading state_dict for TransformerModel

### ISSUE THREAD

**Issue by EduardoPach** [microsoft/muzic#95]
While trying to run the inference test with

```bash
python lyric melody test test_res
```

I got:

```bash
2023-01-15 21:47:23 | INFO | fairseq.tasks.text_to_speech | Please install tensorboardX: pip install tensorboardX
2023-01-15 21:47:23 | INFO | fairseq.file_utils | loading archive file checkpoints/lyric
2023-01-15 21:47:23 | INFO | fairseq.file_utils | loading archive file data-bin/lyric
2023-01-15 21:47:24 | INFO | fairseq.tasks.translation | [lyric] dictionary: 16 types
2023-01-15 21:47:24 | INFO | fairseq.tasks.translation | [beat] dictionary: 4784 types
Traceback (most recent call last):
  File "/home/eduardopach/Projects/muzic/telemelody/inferrence/infer_en.py", line 151, in <module>
    lyric2beats = TransformerModel.from_pretrained(
  File "/home/eduardopach/.local/share/virtualenvs/muzic-CxRwoM1_/lib/python3.10/site-packages/fairseq/models/fairseq_model.py", line 267, in from_pretrained
    x = hub_utils.from_pretrained(
  File "/home/eduardopach/.local/share/virtualenvs/muzic-CxRwoM1_/lib/python3.10/site-packages/fairseq/hub_utils.py", line 73, in from_pretrained
    models, args, task = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/eduardopach/.local/share/virtualenvs/muzic-CxRwoM1_/lib/python3.10/site-packages/fairseq/checkpoint_utils.py", line 482, in load_model_ensemble_and_task
    model.load_state_dict(
  File "/home/eduardopach/.local/share/virtualenvs/muzic-CxRwoM1_/lib/python3.10/site-packages/fairseq/models/fairseq_model.py", line 128, in load_state_dict
    return super().load_state_dict(new_state_dict, strict)
  File "/home/eduardopach/.local/share/virtualenvs/muzic-CxRwoM1_/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for TransformerModel:
        size mismatch for encoder.embed_tokens.weight: copying a param with shape torch.Size([4784, 256]) from checkpoint, the shape in current model is torch.Size([16, 256]).
        size mismatch for decoder.embed_tokens.weight: copying a param with shape torch.Size([16, 256]) from checkpoint, the shape in current model is torch.Size([4784, 256]).
        size mismatch for decoder.output_projection.weight: copying a param with shape torch.Size([16, 256]) from checkpoint, the shape in current model is torch.Size([4784, 256]).
```

I'm running with the following directory structure (ignore t.ipynb)

![image](https://user-images.githubusercontent.com/69953243/212577170-0c933267-61fc-4023-b4e6-e3b73345e18d.png)

not sure what I did wrong, because I can see that dimensions involved match lyrics and beats dicts, but they're not in the correct format. Any ideas? @jzq2000

**Comment by EduardoPach** [comment]
for some reason the dicts had their names swapped haha. Now I don't get that error anymore
